<a href="https://colab.research.google.com/github/ShivaniMohite1/CodeClauseInternship_ProjectName/blob/main/CodeClause_Ds_Internship_Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CodeClause Data Science Internship**

**Golden Projects :-**

**Project 4 :- Prediction of the Next Word**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/content'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/content/1661-0.txt
/content/.config/active_config
/content/.config/config_sentinel
/content/.config/.last_opt_in_prompt.yaml
/content/.config/default_configs.db
/content/.config/.last_survey_prompt.yaml
/content/.config/.last_update_check.json
/content/.config/gce
/content/.config/configurations/config_default
/content/.config/logs/2023.12.04/14.20.49.627769.log
/content/.config/logs/2023.12.04/14.23.49.652015.log
/content/.config/logs/2023.12.04/14.23.59.638040.log
/content/.config/logs/2023.12.04/14.26.59.279282.log
/content/.config/logs/2023.12.04/14.27.00.107426.log
/content/.config/logs/2023.12.04/14.26.48.840108.log
/content/sample_data/anscombe.json
/content/sample_data/README.md
/content/sample_data/california_housing_train.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_train_small.csv


In [ ]:
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

In [ ]:
text_df = open("/content/1661-0.txt")

In [ ]:
text_df

<_io.TextIOWrapper name='/content/1661-0.txt' mode='r' encoding='UTF-8'>

In [ ]:
lst1 = []
for i in text_df:
    lst1.append(i)

In [ ]:
data = ""
for i in lst1:
    data = ' '.join(lst1)

In [ ]:
data = data.replace('\n','')
data = data.replace('\r','')
data = data.replace('\ufeff','')
data = data.replace('“','')
data = data.replace('”','')

In [ ]:
data = data.split()
data = ' '.join(data)
data[:500]

"Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle This eBook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at www.gutenberg.net Title: The Adventures of Sherlock Holmes Author: Arthur Conan Doyle Release Date: November 29, 2002 [EBook #1661] Last Updated: May 20, 2019 Language: English Character set en"

In [ ]:
len(data)

573660

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

In [ ]:
sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[142, 4680, 1, 986, 5, 125, 33, 46, 556, 2164, 2165, 27, 987, 14, 22]

In [ ]:
len(sequence_data)

108958

In [ ]:
sizeofvocab = len(tokenizer.word_index)+1
print(sizeofvocab)

8624


In [ ]:

sequences = []

for i in range(3,len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)

print("Length of sequences: ",len(sequences))
sequences = np.array(sequences)
sequences[:10]

Length of sequences:  108955


array([[ 142, 4680,    1,  986],
       [4680,    1,  986,    5],
       [   1,  986,    5,  125],
       [ 986,    5,  125,   33],
       [   5,  125,   33,   46],
       [ 125,   33,   46,  556],
       [  33,   46,  556, 2164],
       [  46,  556, 2164, 2165],
       [ 556, 2164, 2165,   27],
       [2164, 2165,   27,  987]])

In [ ]:
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])

X = np.array(X)
y = np.array(y)

In [ ]:
print("X:",X[:10])
print("y:",y[:10])

X: [[ 142 4680    1]
 [4680    1  986]
 [   1  986    5]
 [ 986    5  125]
 [   5  125   33]
 [ 125   33   46]
 [  33   46  556]
 [  46  556 2164]
 [ 556 2164 2165]
 [2164 2165   27]]
y: [ 986    5  125   33   46  556 2164 2165   27  987]


In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y,num_classes=sizeofvocab)
y[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential

In [ ]:
model = Sequential()
model.add(Embedding(sizeofvocab, 10, input_length = 3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000,activation='relu'))
model.add(Dense(sizeofvocab, activation="softmax"))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 10)             86240     
                                                                 
 lstm (LSTM)                 (None, 3, 1000)           4044000   
                                                                 
 lstm_1 (LSTM)               (None, 1000)              8004000   
                                                                 
 dense (Dense)               (None, 1000)              1001000   
                                                                 
 dense_1 (Dense)             (None, 8624)              8632624   
                                                                 
Total params: 21767864 (83.04 MB)
Trainable params: 21767864 (83.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate= 0.001), loss="categorical_crossentropy")

In [ ]:
model.fit(X,y,epochs=70,batch_size=64)

In [ ]:
 model.save('next_word_prediction.h5')

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
def Predict_next_words(model,tokenizer,text):

    sequence = tokenizer.texts_to_sequences([text])
    sequence = np.array(sequence)
    preds = np.argmax(model.predict(sequence))

    token = tokenizer.word_index
    k1 = [key for key,value in token.items() if value==preds]
    print(k1)
    return k1

In [ ]:
for i in range(5):
    print("Enter line ",i+1)
    text = input()

    if text == "0":
        print("Execution completed")
        break
    else:
        text = text.split(" ")
        text = text[-3:]
        print(text)

        Predict_next_words(model,tokenizer,text)
        print('\n')

Enter line  1
